services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: [".env"]
    ports:
      - "5432:5432"      # optional: expose locally for psql/DBeaver
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./api
    restart: unless-stopped
    env_file: [".env"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tototoo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin   # <— persist config

  streamlit:
    build: ./streamlit
    restart: unless-stopped
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  db_data:
  pgadmin_data:
